### ISSUE TITLE
./scripts/setup_aws_bosh_for_concourse tries to do ruby interpolation

### ISSUE THREAD

**Issue by luan** [cloudfoundry/mega-ci#10]
`#{cert_name}` is not really valid bash

```
+ openssl req -new -nodes -newkey rsa:2048 -out 'generated-stubs/#{cert_name}.csr' -keyout ../deployments-luan/certs/concourse.key -subj /CN=
```

**Comment by Amit-PivotalLabs** [comment]
Thanks very much for this feedback @luan, we're marking this repo as being under heavy re-construction, and we'll incorporate this information in the new incarnation. (I'll copy-paste this message to the other issues you opened, for anyone in the future coming across any of them).
