### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by anweiss** [cloudfoundry/mega-ci#14]
Interested in script and pipeline support for Azure via the [Azure CPI](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release).

**Comment by Amit-PivotalLabs** [comment]
Hi @anweiss 

We do plan to support Azure in the future, but in the short run we have a lot of work to do get basic AWS support working.  Much of the work in this repo was investigatory, and we'll be approaching it anew as a greenfield project in a week or so.  Further down the line, we definitely plan to add support for Azure, OpenStack, and any other infrastructures that have a means of automating IaaS resource provisioning.
