### ISSUE TITLE
Docker images for concourse pipelines

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/mega-ci#15]
Based on @Amit-PivotalLabs 's email,  the **runtime-ci** Docker image is going to be unsupported soon. 

We currently are using it couple of our pipelines to create a final release. 

What are the recommendations for building clean and small Docker images moving forward? Will there be any new Docker images that will be supported that we can just replace for the task of `creating a bosh release`

**Comment by zankich** [comment]
@tushar-dadlani we've created a small set of curated docker images to satisfy our CI needs. You can look at the dockerfiles we've created [here](https://github.com/cloudfoundry/mega-ci/tree/master/dockerfiles) and our CI for building and uploading our docker images [here](https://mega.ci.cf-app.com/pipelines/mega-ci). 

You may be particularly interested in our [deployment](https://github.com/cloudfoundry/mega-ci/blob/master/dockerfiles/deployment/Dockerfile) docker image.  This image contains the bosh cli and everything you'd need to create releases.

I hope this helps point you in the right direction, and if you have any questions please let us know!
