### ISSUE TITLE
Document the need for an IAM user/credentials

### ISSUE THREAD

**Issue by luan** [cloudfoundry/mega-ci#7]
The README doesn't mention the need for a user, or which permissions to assign to a user. I've assigned admin permissions. But it'd also be nice if the README taught me how to do those things.

**Comment by Amit-PivotalLabs** [comment]
Thanks very much for this feedback @luan, we're marking this repo as being under heavy re-construction, and we'll incorporate this information in the new incarnation. (I'll copy-paste this message to the other issues you opened, for anyone in the future coming across any of them).
