### ISSUE TITLE
Should DEPLOYMENT_DIR be part of requirements?

### ISSUE THREAD

**Issue by luan** [cloudfoundry/mega-ci#8]
On the README, I was confused when **Usage** mentioned a `PATH_TO_DEPLOYMENT_DIR`. The lines below will explain what that is, but it took me a bit to figure out that it would explain it later, only to make me scroll back up later.

That flow could be improved for the reader.

**Comment by Amit-PivotalLabs** [comment]
I think this is specific to the CF tool.  For the Concourse tool, it says:

> Usage

> ./scripts/setup_aws_bosh_for_concourse PATH_TO_DEPLOYMENT_DIR

> See Requirements below for an explanation of the DEPLOYMENT_DIR.

I'll update the story and prioritize it.

**Comment by Amit-PivotalLabs** [comment]
Thanks very much for this feedback @luan, we're marking this repo as being under heavy re-construction, and we'll incorporate this information in the new incarnation. (I'll copy-paste this message to the other issues you opened, for anyone in the future coming across any of them).
